# Z Linux - fuzzel (minimo; fase 2 trae temas omarchy)
font=monospace:size=11
terminal=foot -e
prompt=❯
icon-theme=Papirus
icons-enabled=yes
fields=name,generic,filename
width=45
lines=15

[colors]
background=1d2021f2
text=ebdbb2ff
match=83a598ff
selection=458588ff
selection-text=ebdbb2ff
selection-match=83a598ff
border=928374ff
